### ISSUE TITLE
R not found

### ISSUE THREAD

**Issue by Yousuf28** [r-wasm/actions#11]
I was trying to setup github action to build R package for werbr.  I got following error.

```
Run r-wasm/actions/build-wasm-packages@v1
  with:
    strip: c("demo", "doc", "examples", "help", "html", "include", "tests", "vignette")
    packages: packages
    upload-image: true
    upload-repo: true
Run /usr/bin/R --silent -e 'install.packages("pak")'
  /usr/bin/R --silent -e 'install.packages("pak")'
  /usr/bin/R --silent -e 'pak::pak("r-wasm/rwasm")'
  shell: bash --noprofile --norc -e -o pipefail {0}
/__w/_temp/34ffc0ae-0eea-4442-bb8f-4d27b73f4a11.sh: line 1: /usr/bin/R: No such file or directory
Error: Process completed with exit code 127.
```

- [yml file here](https://github.com/Yousuf28/webr_build/blob/main/.github/workflows/build.yml)

**Comment by georgestagg** [comment]
We're currently working on improving this process with a reusable workflow system, so things are a little unstable right now on the v1 branch.

For the moment, please try again using `r-wasm/actions/build-wasm-packages@v0.0.3`.

**Comment by Yousuf28** [comment]
Thanks @georgestagg. After I changed that line the build was successful. 
 On github action page I can see all the artifact that generated from build process. But on my github page 
 [link](https://yousuf28.github.io/webr_build/) I don't see anything.
in webr REPL, I tried 
`webr::install("fs", repos = "http://yousuf28.github.io/webr_build/")`
I get following error
```
Warning: unable to access index for repository http://yousuf28.github.io/webr_build/bin/emscripten/contrib/4.3:
  download from 'http://yousuf28.github.io/webr_build/bin/emscripten/contrib/4.3/PACKAGES' failed
Warning message:
In webr::install("fs", repos = "http://yousuf28.github.io/webr_build/") :
  Requested package fs not found in webR binary repo.
```
How to solve this issue?

**Comment by georgestagg** [comment]
For security reasons a HTTPS connection is required from webR.

Try,
```r
webr::install("fs", repos = "https://yousuf28.github.io/webr_build")
```

**Comment by Yousuf28** [comment]
That worked. Thank you so much for help.
